import { certificates } from './certificates';
import { projects } from './projects';

export const DATA = {
  projects,
  certificates,
  contacts: [
    {
      contId: 1,
      href: 'https://www.linkedin.com/in/bhushanmhatre',
      name: 'linkedin',
      icon: 'fa fa-linkedin fa-lg',
      color: '#0072b1',
      darkColor: '#70b5f9',
    },
    {
      contId: 2,
      href: 'https://github.com/thebhushanmhatre',
      name: 'github',
      icon: 'fa fa-github fa-lg',
      color: 'black',
      darkColor: 'white',
    },
    {
      contId: 3,
      href: 'https://www.freecodecamp.org/thebhushanmhatre',
      name: 'freeCodeCamp',
      icon: 'fa fa-free-code-camp fa-lg',
      color: 'green',
      darkColor: '#39e09b',
    },
    {
      contId: 7,
      href: 'https://leetcode.com/u/bhushanmhatre/',
      name: 'leetcode',
      icon: 'fas fa-code fa-lg',
      color: '#B45309',
      darkColor: '#ffa116',
    },
    {
      contId: 8,
      href: 'https://codesandbox.io/u/thebhushanmhatre',
      name: 'codeSandbox',
      icon: 'fas fa-code fa-lg',
      color: 'purple',
      darkColor: '#bb86fc',
    },
    {
      contId: 5,
      href: 'https://www.hackerrank.com/bhushanmhatre',
      name: 'hackerrank',
      icon: 'fab fa-hackerrank fa-lg',
      color: 'green',
      darkColor: '#2ec866',
    },
    {
      contId: 6,
      href: 'https://www.kaggle.com/thebhushanmhatre',
      name: 'kaggle',
      icon: 'fab fa-kaggle fa-lg',
      color: '#2977c9',
      darkColor: '#20beff',
    },
    {
      contId: 4,
      href: 'https://codepen.io/thebhushanmhatre/',
      name: 'codepen',
      icon: 'fa fa-codepen fa-lg',
      color: 'black',
      darkColor: 'white',
    },
  ],
  career: [
    {
      id: 'born',
      year: '1997',
      label: 'Born',
      lineText: null,
      type: 'born',
    },
    {
      id: 'school',
      year: '2013',
      label: 'Completed School',
      lineText: null,
      type: 'education',
      href: 'https://en.wikipedia.org/wiki/Saint_Francis_D%27Assisi_High_School',
      name: "St. Francis D'Assisi High School",
      src: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Sfhs1.jpg',
      degree: 'School',
      description:
        "Completed my schooling at St. Francis D'Assisi High School (SFHS), passing SSC exams in 2013 with 90% (145/150 in Mathematics, 97/100 in Science).",
    },
    {
      id: 'patkar',
      year: '2015',
      label: 'Patkar College',
      lineText: null,
      type: 'education',
      href: 'https://www.patkarvardecollege.edu.in/',
      name: 'Patkar College of Science',
      src: 'https://content.jdmagicbox.com/v2/comp/mumbai/m5/022pxx22.xx22.210903125653.m6m5/catalogue/chikitsak-samuha-s-patkar-varde-college-goregaon-west-mumbai-colleges-0vvrqdhisj.jpg',
      degree: 'Junior College (Science)',
      description:
        'Completed junior college from Patkar College of Science with specialization in Electronics and Psychology elective.',
    },
    {
      id: 'vjti',
      year: '2019',
      label: 'Graduated from VJTI🎓',
      lineText: null,
      type: 'education',
      href: 'https://vjti.ac.in/',
      name: 'Veermata Jijabai Techological Institute',
      src: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/VJTI_Quadrangle.jpg',
      degree: 'B.Tech.',
      description: [
        `I graduated with a Bachelor of Technology (B.Tech.) in Electronics and Telecommunication Engineering from the prestigious Veermata Jijabai Technological Institute (VJTI), one of India's premier engineering institutes. My academic journey provided me with a strong foundation in both theoretical concepts and practical engineering applications, particularly in communication systems, signal processing, and embedded technologies.`,
        `During my undergraduate studies, I explored a wide range of subjects, including Digital Signal Processing, Digital Image Processing, Data Compression, Computer Communication Networks, Antenna Design, VLSI Design, Pattern Recognition, Microprocessor and Microcontroller Systems, and Embedded Systems. I also built strong programming and systems knowledge through courses such as Computer Programming (C/C++), Java, and Data Structures & Algorithms, which helped pave my way toward a career in software engineering.`,
        `For my Final Year Project, I worked on "Wireless Transmission using Low Density Parity Check (LDPC) Codes." The project focused on implementing data encryption, error correction, and wireless transmission between two Raspberry Pi devices, utilizing LDPC codes and a Python-based Tkinter GUI.`,
      ],
    },
    {
      id: 'analyst',
      year: '2022',
      label: 'Promotion✨',
      lineText: 'Analyst @ MSCI',
      type: 'work',
    },
    {
      id: 'associate',
      year: '2026',
      // label: 'Joined JP Morgan Chase🎉',
      label: 'Left MSCI',
      lineText: 'Associate @ MSCI',
      type: 'work',
    },
    {
      id: 'present',
      year: 'Present',
      label: '',
      lineText: 'Upskilling...',
      type: 'present',
    },
  ],
};
