import { certificates } from './certificates';
import { projects } from './projects';

export const DATA = {
  projects,
  certificates,
  contacts: [
    {
      contId: 2,
      href: 'https://github.com/thebhushanmhatre',
      name: 'github',
      icon: 'fa fa-github fa-lg',
      color: 'black',
    },
    {
      contId: 1,
      href: 'https://www.linkedin.com/in/bhushanmhatre',
      name: 'linkedin',
      icon: 'fa fa-linkedin fa-lg',
      color: '#2977c9',
    },
    {
      contId: 3,
      href: 'https://www.freecodecamp.org/thebhushanmhatre',
      name: 'freeCodeCamp',
      icon: 'fa fa-free-code-camp fa-lg',
      color: 'green',
    },
    {
      contId: 7,
      href: 'https://leetcode.com/u/bhushanmhatre/',
      name: 'leetcode',
      icon: 'fas fa-code fa-lg',
      color: '#B45309',
    },
    {
      contId: 8,
      href: 'https://codesandbox.io/u/thebhushanmhatre',
      name: 'codeSandbox',
      icon: 'fas fa-code fa-lg',
      color: 'purple',
    },
    {
      contId: 5,
      href: 'https://www.hackerrank.com/bhushanmhatre',
      name: 'hackerrank',
      icon: 'fab fa-hackerrank fa-lg',
      color: 'green',
    },
    {
      contId: 6,
      href: 'https://www.kaggle.com/thebhushanmhatre',
      name: 'kaggle',
      icon: 'fab fa-kaggle fa-lg',
      color: '#2977c9',
    },
    {
      contId: 4,
      href: 'https://codepen.io/thebhushanmhatre/',
      name: 'codepen',
      icon: 'fa fa-codepen fa-lg',
      color: 'black',
    },
  ],
  career: [
    {
      id: 'born',
      year: '1997',
      label: 'Born',
      lineText: null,
      type: 'born',
    },
    {
      id: 'school',
      year: '2013',
      label: 'Completed School',
      lineText: null,
      type: 'education',
      href: 'https://en.wikipedia.org/wiki/Saint_Francis_D%27Assisi_High_School',
      name: "St. Francis D'Assisi High School",
      src: 'assets/images/sfhs_logo.jpg',
      degree: 'School',
    },
    {
      id: 'patkar',
      year: '2015',
      label: 'Patkar College',
      lineText: null,
      type: 'education',
      href: 'https://www.patkarvardecollege.edu.in/',
      name: 'Patkar College of Science',
      src: 'assets/images/patkar_logo.jpg',
      degree: 'Junior College (Science)',
    },
    {
      id: 'vjti',
      year: '2019',
      label: 'Graduated from VJTI🎓',
      lineText: null,
      type: 'education',
      href: 'https://vjti.ac.in/',
      name: 'Veermata Jijabai Techological Institute',
      src: 'assets/images/vjti_logo.jpg',
      degree: 'B.Tech.',
    },
    {
      id: 'analyst',
      year: '2022',
      label: 'Promotion✨',
      lineText: 'Analyst @ MSCI',
      type: 'work',
    },
    {
      id: 'associate',
      year: '2026',
      label: 'Joined JP Morgan Chase🎉',
      lineText: 'Associate @ MSCI',
      type: 'work',
    },
    {
      id: 'present',
      year: 'Present',
      label: '',
      lineText: null,
      type: 'present',
    },
  ],
};
