export const projects = [
  {
    projectId: 22,
    tag: 'codesandbox',
    href: 'https://5rmdcm.csb.app/',
    src: 'assets/images/projects/radar.jpg',
    tech: ['React'],
    name: 'Classic Snake Game',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 27,
    tag: 'codesandbox',
    href: 'https://sj5x54.csb.app/',
    src: 'assets/images/projects/radar.jpg',
    tech: ['React'],
    name: 'Sudoku Game',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 23,
    tag: 'codesandbox',
    href: 'https://7d5cnt.csb.app/',
    src: 'assets/images/projects/radar.jpg',
    tech: ['React'],
    name: 'Whack a Mole Game',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 24,
    tag: 'codesandbox',
    href: 'https://5ngqk6.csb.app/',
    src: 'assets/images/projects/radar.jpg',
    tech: ['React'],
    name: 'Memory Game',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 26,
    tag: 'codesandbox',
    href: 'https://j5hk6v.csb.app/',
    src: 'assets/images/projects/radar.jpg',
    tech: ['React'],
    name: 'Nested Checkboxes with Indeterminate',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 25,
    tag: 'codesandbox',
    href: 'https://8np9gq.csb.app/',
    src: 'assets/images/projects/radar.jpg',
    tech: ['React', 'Javascript', 'Fetch API'],
    name: 'Pokemon List',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 1,
    tag: 'inbuilt',
    href: '/recipes',
    src: 'assets/images/projects/recipe-app.jpg',
    tech: ['React', 'Javascript', 'Fetch API'],
    name: 'Recipe App',
    visible: true,
    target: '',
  },
  {
    projectId: 2,
    tag: 'inbuilt',
    href: '/quotes', //https://codepen.io/thebhushanmhatre/full/yZQmVw"
    src: 'assets/images/projects/quotes.jpg',
    tech: ['Javascript'],
    name: 'Random Quote Machine',
    visible: true,
    target: '',
  },
  {
    projectId: 4,
    tag: 'inbuilt',
    href: '/markdown',
    src: 'assets/images/projects/markdown.jpg',
    tech: ['Javascript'],
    name: 'Markdown Previewer',
    visible: true,
    target: '',
  },
  {
    projectId: 5,
    tag: 'inbuilt',
    href: '/clock', //https://codepen.io/thebhushanmhatre/full/LaJqvy",
    src: 'assets/images/projects/clock.jpg',
    tech: ['Javascript'],
    name: 'Pomodoro Clock',
    visible: true,
    target: '',
  },
  {
    projectId: 7,
    tag: 'codepen',
    href: 'https://codepen.io/thebhushanmhatre/full/BbPrwa',
    src: 'assets/images/projects/calculator.jpg',
    tech: ['Javascript'],
    name: 'Simple Calculator',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 8,
    tag: 'codepen',
    href: 'https://codepen.io/thebhushanmhatre/full/QYeKBy',
    src: 'assets/images/projects/drum.jpg',
    tech: ['Javascript'],
    name: 'Drum Machine',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 12,
    href: '',
    src: 'assets/images/projects/senti.jpg',
    tech: ['Python', 'Machine Learning'],
    name: 'Sentiment Analysis',
    visible: false,
    target: '',
  },
  {
    projectId: 11,
    tag: 'kaggle',
    href: 'https://www.kaggle.com/thebhushanmhatre/my-firsttry-on-kaggle/',
    src: 'assets/images/projects/titanic.jpg',
    tech: ['Python', 'Machine Learning'],
    name: 'Titanic - Predicting Survival based on Ticket Number',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 13,
    href: '',
    src: 'assets/images/projects/radar.jpg',
    tech: ['Electronics'],
    name: 'Arduino Radar',
    visible: false,
    target: '_blank',
  },
  {
    projectId: 14,
    href: '',
    src: 'assets/images/projects/robarm.jpg',
    tech: ['Electronics'],
    name: 'Haptic Robotic Arm',
    visible: false,
    target: '_blank',
  },
  {
    projectId: 17,
    tag: 'github',
    href: 'https://github.com/thebhushanmhatre/Tetris',
    src: 'assets/images/projects/tetris_js.jpg',
    tech: ['JavaScript', 'Game'],
    name: 'Tetris Game',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 15,
    href: 'assets/notebooks/WebScraping.html',
    src: 'assets/images/projects/web_scrapping.jpg',
    tech: ['Python', 'Web Scrapping'],
    name: 'Web Scrapping using Beautiful Soup',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 16,
    href: 'assets/notebooks/Handwashing.html',
    src: 'assets/images/projects/hand_washing.jpg',
    tech: ['Python', 'Data Analysis'],
    name: 'Wash your Hands says the Data',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 18,
    tag: 'github',
    href: 'https://github.com/thebhushanmhatre/url-shortener',
    src: 'assets/images/projects/url_shortener.jpg',
    tech: ['Python'],
    name: 'Url-Shortner',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 20,
    tag: 'github',
    href: 'https://github.com/thebhushanmhatre/JSProjects',
    src: 'assets/images/projects/js_apps.jpg',
    tech: ['Javascript'],
    name: 'Vanilla Javascript based Apps (for Fun)',
    visible: true,
    target: '_blank',
  },
];
