export const projects = [
	{
		projectId: 22,
		tag: "codesandbox",
		href: "https://5rmdcm.csb.app/",
		tech: ["React"],
		name: "Classic Snake Game",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 27,
		tag: "codesandbox",
		href: "https://sj5x54.csb.app/",
		tech: ["React"],
		name: "Sudoku Game",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 23,
		tag: "codesandbox",
		href: "https://7d5cnt.csb.app/",
		tech: ["React"],
		name: "Whack a Mole Game",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 24,
		tag: "codesandbox",
		href: "https://5ngqk6.csb.app/",
		tech: ["React"],
		name: "Memory Game",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 26,
		tag: "codesandbox",
		href: "https://j5hk6v.csb.app/",
		tech: ["React"],
		name: "Nested Checkboxes with Indeterminate",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 25,
		tag: "codesandbox",
		href: "https://8np9gq.csb.app/",
		tech: ["React", "Javascript", "Fetch API"],
		name: "Pokemon List",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 1,
		tag: "inbuilt",
		href: "/recipes",
		tech: ["React", "Javascript", "Fetch API"],
		name: "Recipe App",
		visible: true,
		target: "",
	},
	{
		projectId: 2,
		tag: "inbuilt",
		href: "/quotes", //https://codepen.io/thebhushanmhatre/full/yZQmVw"		tech: ["Javascript"],
		name: "Random Quote Machine",
		visible: true,
		target: "",
	},
	{
		projectId: 4,
		tag: "inbuilt",
		href: "/markdown",
		tech: ["Javascript"],
		name: "Markdown Previewer",
		visible: true,
		target: "",
	},
	{
		projectId: 5,
		tag: "inbuilt",
		href: "/clock", //https://codepen.io/thebhushanmhatre/full/LaJqvy",		tech: ["Javascript"],
		name: "Pomodoro Clock",
		visible: true,
		target: "",
	},
	{
		projectId: 7,
		tag: "codepen",
		href: "https://codepen.io/thebhushanmhatre/full/BbPrwa",
		tech: ["Javascript"],
		name: "Simple Calculator",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 8,
		tag: "codepen",
		href: "https://codepen.io/thebhushanmhatre/full/QYeKBy",
		tech: ["Javascript"],
		name: "Drum Machine",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 12,
		href: "",
		tech: ["Python", "Machine Learning"],
		name: "Sentiment Analysis",
		visible: false,
		target: "",
	},
	{
		projectId: 11,
		tag: "kaggle",
		href: "https://www.kaggle.com/thebhushanmhatre/my-firsttry-on-kaggle/",
		tech: ["Python", "Machine Learning"],
		name: "Titanic - Predicting Survival based on Ticket Number",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 13,
		href: "",
		tech: ["Electronics"],
		name: "Arduino Radar",
		visible: false,
		target: "_blank",
	},
	{
		projectId: 14,
		href: "",
		tech: ["Electronics"],
		name: "Haptic Robotic Arm",
		visible: false,
		target: "_blank",
	},
	{
		projectId: 17,
		tag: "github",
		href: "https://github.com/thebhushanmhatre/Tetris",
		tech: ["JavaScript", "Game"],
		name: "Tetris Game",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 15,
		href: "assets/notebooks/WebScraping.html",
		tech: ["Python", "Web Scrapping"],
		name: "Web Scrapping using Beautiful Soup",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 16,
		href: "assets/notebooks/Handwashing.html",
		tech: ["Python", "Data Analysis"],
		name: "Wash your Hands says the Data",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 18,
		tag: "github",
		href: "https://github.com/thebhushanmhatre/url-shortener",
		tech: ["Python"],
		name: "Url-Shortner",
		visible: true,
		target: "_blank",
	},
	{
		projectId: 20,
		tag: "github",
		href: "https://github.com/thebhushanmhatre/JSProjects",
		tech: ["Javascript"],
		name: "Vanilla Javascript based Apps (for Fun)",
		visible: true,
		target: "_blank",
	},
];
