export const projects = [
  {
    projectId: 21,
    inbuilt: true,
    href: '/card-game',
    src: 'assets/images/projects/cardgame.jpg',
    tech: ['React', 'Javascript'],
    name: 'Card Game',
    visible: true,
    target: '',
  },
  {
    projectId: 1,
    inbuilt: true,
    href: '/recipes',
    src: 'assets/images/projects/recipe-app.jpg',
    tech: ['React', 'Javascript', 'Fetch API'],
    name: 'Recipe App',
    visible: true,
    target: '',
  },
  {
    projectId: 2,
    inbuilt: true,
    href: '/quotes', //https://codepen.io/thebhushanmhatre/full/yZQmVw"
    src: 'assets/images/projects/quotes.jpg',
    tech: ['Javascript'],
    name: 'Random Quote Machine',
    visible: true,
    target: '',
  },
  {
    projectId: 3,
    inbuilt: true,
    href: '/todolist',
    src: 'assets/images/projects/todoapp.jpg',
    tech: ['React', 'Javascript'],
    name: 'To Do List App',
    visible: true,
    target: '',
  },
  {
    projectId: 4,
    inbuilt: true,
    href: '/markdown',
    src: 'assets/images/projects/markdown.jpg',
    tech: ['Javascript'],
    name: 'Markdown Previewer',
    visible: true,
    target: '',
  },
  {
    projectId: 5,
    inbuilt: true,
    href: '/clock', //https://codepen.io/thebhushanmhatre/full/LaJqvy",
    src: 'assets/images/projects/clock.jpg',
    tech: ['Javascript'],
    name: 'Pomodoro Clock',
    visible: true,
    target: '',
  },
  {
    projectId: 6,
    inbuilt: false,
    href: 'https://github.com/thebhushanmhatre/book_flights',
    src: 'assets/images/projects/bookflight.jpg',
    tech: ['Ruby', 'Ruby on Rails'],
    name: 'Flight Booking App',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 7,
    inbuilt: false,
    href: 'https://codepen.io/thebhushanmhatre/full/BbPrwa',
    src: 'assets/images/projects/calculator.jpg',
    tech: ['Javascript'],
    name: 'Simple Calculator',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 8,
    inbuilt: false,
    href: 'https://codepen.io/thebhushanmhatre/full/QYeKBy',
    src: 'assets/images/projects/drum.jpg',
    tech: ['Javascript'],
    name: 'Drum Machine',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 9,
    inbuilt: false,
    href: 'https://codepen.io/thebhushanmhatre/full/KJbZrY',
    src: 'assets/images/projects/bookmark.jpg',
    tech: ['Javascript'],
    name: 'Bookmark App',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 10,
    inbuilt: false,
    href: 'https://codepen.io/thebhushanmhatre/full/aXPoNw',
    src: 'assets/images/projects/weights.jpg',
    tech: ['Javascript'],
    name: 'Intergallatic Weights',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 12,
    inbuilt: false,
    href: '',
    src: 'assets/images/projects/senti.jpg',
    tech: ['Python', 'Machine Learning'],
    name: 'Sentiment Analysis',
    visible: false,
    target: '',
  },
  {
    projectId: 11,
    inbuilt: false,
    href: 'https://www.kaggle.com/thebhushanmhatre/my-firsttry-on-kaggle/',
    src: 'assets/images/projects/titanic.jpg',
    tech: ['Python', 'Machine Learning'],
    name: 'Kaggle: Titanic Dataset',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 13,
    inbuilt: false,
    href: '',
    src: 'assets/images/projects/radar.jpg',
    tech: ['Electronics'],
    name: 'Arduino Radar',
    visible: false,
    target: '_blank',
  },
  {
    projectId: 14,
    inbuilt: false,
    href: '',
    src: 'assets/images/projects/robarm.jpg',
    tech: ['Electronics'],
    name: 'Haptic Robotic Arm',
    visible: false,
    target: '_blank',
  },
  {
    projectId: 17,
    inbuilt: false,
    href: 'https://github.com/thebhushanmhatre/Tetris',
    src: 'assets/images/projects/tetris_js.jpg',
    tech: ['JavaScript', 'Game'],
    name: 'Tetris Game',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 15,
    inbuilt: false,
    href: 'assets/notebooks/WebScraping.html',
    src: 'assets/images/projects/web_scrapping.jpg',
    tech: ['Python', 'Web Scrapping'],
    name: 'Web Scrapping using Beautiful Soup',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 16,
    inbuilt: false,
    href: 'assets/notebooks/Handwashing.html',
    src: 'assets/images/projects/hand_washing.jpg',
    tech: ['Python', 'Data Analysis'],
    name: 'Wash your Hands says the Data',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 18,
    inbuilt: false,
    href: 'https://github.com/thebhushanmhatre/url-shortener',
    src: 'assets/images/projects/url_shortener.jpg',
    tech: ['Python'],
    name: 'Url-Shortner',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 19,
    inbuilt: false,
    href: 'https://github.com/thebhushanmhatre/react-flask-app',
    src: 'assets/images/projects/react_flask_app.jpg',
    tech: ['Javascript', 'Python', 'React', 'Flask'],
    name: 'React-Flask App',
    visible: true,
    target: '_blank',
  },
  {
    projectId: 20,
    inbuilt: false,
    href: 'https://github.com/thebhushanmhatre/JSProjects',
    src: 'assets/images/projects/js_apps.jpg',
    tech: ['Javascript'],
    name: 'Javascript App',
    visible: false,
    target: '_blank',
  },
];
